service: ignitecertificate

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  profile: default
  memorySize: 256 # optional, in MB, default is 1024
  stage: dev

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  hello:
    handler: src/functions/hello.handle # required, handler set in AWS Lambda
    name: "${self:service}-${self:provider.stage}" # optional, Deployed Lambda name
    description: "Ignite Serverless"
    events:
      - http:
          path: /hello
          method: get
          cors: true